name: Android CI

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      reason:
        description: 'Manual trigger reason'
        required: false
        default: 'manual'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Use the Gradle Build Action to run the assembleRelease task without requiring a wrapper
      - name: Build release APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease
          gradle-version: '8.2'

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
